# Generated by Django 5.2.5 on 2025-10-31 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polizas',
            name='id_tipo_poliza',
        ),
    ]
